# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maindesign.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1097, 576)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1, 1))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.maingrid = QtWidgets.QGridLayout()
        self.maingrid.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.maingrid.setObjectName("maingrid")
        self.keyboardgrid = QtWidgets.QGridLayout()
        self.keyboardgrid.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.keyboardgrid.setSpacing(12)
        self.keyboardgrid.setObjectName("keyboardgrid")
        self.NButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NButton.sizePolicy().hasHeightForWidth())
        self.NButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.NButton.setFont(font)
        self.NButton.setObjectName("NButton")
        self.keyboardgrid.addWidget(self.NButton, 2, 0, 1, 1)
        self.LBracketButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBracketButton.sizePolicy().hasHeightForWidth())
        self.LBracketButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.LBracketButton.setFont(font)
        self.LBracketButton.setObjectName("LBracketButton")
        self.keyboardgrid.addWidget(self.LBracketButton, 1, 4, 1, 1)
        self.N1Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.N1Button.sizePolicy().hasHeightForWidth())
        self.N1Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.N1Button.setFont(font)
        self.N1Button.setObjectName("N1Button")
        self.keyboardgrid.addWidget(self.N1Button, 0, 0, 1, 1)
        self.EqualButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EqualButton.sizePolicy().hasHeightForWidth())
        self.EqualButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.EqualButton.setFont(font)
        self.EqualButton.setObjectName("EqualButton")
        self.keyboardgrid.addWidget(self.EqualButton, 2, 3, 1, 1)
        self.UButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UButton.sizePolicy().hasHeightForWidth())
        self.UButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.UButton.setFont(font)
        self.UButton.setObjectName("UButton")
        self.keyboardgrid.addWidget(self.UButton, 2, 2, 1, 1)
        self.FButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FButton.sizePolicy().hasHeightForWidth())
        self.FButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.FButton.setFont(font)
        self.FButton.setObjectName("FButton")
        self.keyboardgrid.addWidget(self.FButton, 1, 0, 1, 1)
        self.RBracketButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RBracketButton.sizePolicy().hasHeightForWidth())
        self.RBracketButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.RBracketButton.setFont(font)
        self.RBracketButton.setObjectName("RBracketButton")
        self.keyboardgrid.addWidget(self.RBracketButton, 1, 5, 1, 1)
        self.LMBracketButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LMBracketButton.sizePolicy().hasHeightForWidth())
        self.LMBracketButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.LMBracketButton.setFont(font)
        self.LMBracketButton.setObjectName("LMBracketButton")
        self.keyboardgrid.addWidget(self.LMBracketButton, 2, 4, 1, 1)
        self.NewlineButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NewlineButton.sizePolicy().hasHeightForWidth())
        self.NewlineButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.NewlineButton.setFont(font)
        self.NewlineButton.setObjectName("NewlineButton")
        self.keyboardgrid.addWidget(self.NewlineButton, 0, 6, 1, 1)
        self.BackspaceButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BackspaceButton.sizePolicy().hasHeightForWidth())
        self.BackspaceButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.BackspaceButton.setFont(font)
        self.BackspaceButton.setObjectName("BackspaceButton")
        self.keyboardgrid.addWidget(self.BackspaceButton, 0, 5, 1, 1)
        self.N2Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.N2Button.sizePolicy().hasHeightForWidth())
        self.N2Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.N2Button.setFont(font)
        self.N2Button.setObjectName("N2Button")
        self.keyboardgrid.addWidget(self.N2Button, 0, 1, 1, 1)
        self.N3Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.N3Button.sizePolicy().hasHeightForWidth())
        self.N3Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.N3Button.setFont(font)
        self.N3Button.setObjectName("N3Button")
        self.keyboardgrid.addWidget(self.N3Button, 0, 2, 1, 1)
        self.N4Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.N4Button.sizePolicy().hasHeightForWidth())
        self.N4Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.N4Button.setFont(font)
        self.N4Button.setObjectName("N4Button")
        self.keyboardgrid.addWidget(self.N4Button, 0, 3, 1, 1)
        self.N5Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.N5Button.sizePolicy().hasHeightForWidth())
        self.N5Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.N5Button.setFont(font)
        self.N5Button.setObjectName("N5Button")
        self.keyboardgrid.addWidget(self.N5Button, 0, 4, 1, 1)
        self.RMBracketButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RMBracketButton.sizePolicy().hasHeightForWidth())
        self.RMBracketButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.RMBracketButton.setFont(font)
        self.RMBracketButton.setObjectName("RMBracketButton")
        self.keyboardgrid.addWidget(self.RMBracketButton, 2, 5, 1, 1)
        self.SButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SButton.sizePolicy().hasHeightForWidth())
        self.SButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.SButton.setFont(font)
        self.SButton.setObjectName("SButton")
        self.keyboardgrid.addWidget(self.SButton, 2, 1, 1, 1)
        self.LButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LButton.sizePolicy().hasHeightForWidth())
        self.LButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.LButton.setFont(font)
        self.LButton.setObjectName("LButton")
        self.keyboardgrid.addWidget(self.LButton, 1, 1, 1, 1)
        self.RunButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunButton.sizePolicy().hasHeightForWidth())
        self.RunButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.RunButton.setFont(font)
        self.RunButton.setAutoFillBackground(False)
        self.RunButton.setObjectName("RunButton")
        self.keyboardgrid.addWidget(self.RunButton, 1, 6, 1, 1)
        self.StopButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StopButton.sizePolicy().hasHeightForWidth())
        self.StopButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.StopButton.setFont(font)
        self.StopButton.setAutoFillBackground(False)
        self.StopButton.setObjectName("StopButton")
        self.keyboardgrid.addWidget(self.StopButton, 2, 6, 1, 1)
        self.BButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BButton.sizePolicy().hasHeightForWidth())
        self.BButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.BButton.setFont(font)
        self.BButton.setObjectName("BButton")
        self.keyboardgrid.addWidget(self.BButton, 1, 3, 1, 1)
        self.RButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RButton.sizePolicy().hasHeightForWidth())
        self.RButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.RButton.setFont(font)
        self.RButton.setObjectName("RButton")
        self.keyboardgrid.addWidget(self.RButton, 1, 2, 1, 1)
        self.IfButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IfButton.sizePolicy().hasHeightForWidth())
        self.IfButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.IfButton.setFont(font)
        self.IfButton.setObjectName("IfButton")
        self.keyboardgrid.addWidget(self.IfButton, 3, 0, 1, 1)
        self.ElseButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ElseButton.sizePolicy().hasHeightForWidth())
        self.ElseButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.ElseButton.setFont(font)
        self.ElseButton.setObjectName("ElseButton")
        self.keyboardgrid.addWidget(self.ElseButton, 3, 1, 1, 1)
        self.WhileButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WhileButton.sizePolicy().hasHeightForWidth())
        self.WhileButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.WhileButton.setFont(font)
        self.WhileButton.setObjectName("WhileButton")
        self.keyboardgrid.addWidget(self.WhileButton, 3, 2, 1, 1)
        self.maingrid.addLayout(self.keyboardgrid, 2, 1, 1, 1)
        self.textgrid = QtWidgets.QGridLayout()
        self.textgrid.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.textgrid.setSpacing(0)
        self.textgrid.setObjectName("textgrid")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.textgrid.addWidget(self.textEdit, 0, 0, 1, 1)
        self.maingrid.addLayout(self.textgrid, 1, 1, 1, 1)
        self.blankgrid = QtWidgets.QGridLayout()
        self.blankgrid.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.blankgrid.setSpacing(0)
        self.blankgrid.setObjectName("blankgrid")
        self.label34 = QtWidgets.QLabel(self.centralwidget)
        self.label34.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label34.sizePolicy().hasHeightForWidth())
        self.label34.setSizePolicy(sizePolicy)
        self.label34.setMinimumSize(QtCore.QSize(50, 50))
        self.label34.setSizeIncrement(QtCore.QSize(1, 1))
        self.label34.setBaseSize(QtCore.QSize(50, 50))
        self.label34.setFrameShape(QtWidgets.QFrame.Box)
        self.label34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label34.setLineWidth(1)
        self.label34.setText("")
        self.label34.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label34.setScaledContents(True)
        self.label34.setObjectName("label34")
        self.blankgrid.addWidget(self.label34, 3, 2, 1, 1)
        self.label41 = QtWidgets.QLabel(self.centralwidget)
        self.label41.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label41.sizePolicy().hasHeightForWidth())
        self.label41.setSizePolicy(sizePolicy)
        self.label41.setMinimumSize(QtCore.QSize(50, 50))
        self.label41.setSizeIncrement(QtCore.QSize(1, 1))
        self.label41.setBaseSize(QtCore.QSize(50, 50))
        self.label41.setFrameShape(QtWidgets.QFrame.Box)
        self.label41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label41.setLineWidth(1)
        self.label41.setText("")
        self.label41.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label41.setScaledContents(True)
        self.label41.setObjectName("label41")
        self.blankgrid.addWidget(self.label41, 0, 3, 1, 1)
        self.label21 = QtWidgets.QLabel(self.centralwidget)
        self.label21.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label21.sizePolicy().hasHeightForWidth())
        self.label21.setSizePolicy(sizePolicy)
        self.label21.setMinimumSize(QtCore.QSize(50, 50))
        self.label21.setSizeIncrement(QtCore.QSize(1, 1))
        self.label21.setBaseSize(QtCore.QSize(50, 50))
        self.label21.setFrameShape(QtWidgets.QFrame.Box)
        self.label21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label21.setLineWidth(1)
        self.label21.setText("")
        self.label21.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label21.setScaledContents(True)
        self.label21.setObjectName("label21")
        self.blankgrid.addWidget(self.label21, 0, 1, 1, 1)
        self.label44 = QtWidgets.QLabel(self.centralwidget)
        self.label44.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label44.sizePolicy().hasHeightForWidth())
        self.label44.setSizePolicy(sizePolicy)
        self.label44.setMinimumSize(QtCore.QSize(50, 50))
        self.label44.setSizeIncrement(QtCore.QSize(1, 1))
        self.label44.setBaseSize(QtCore.QSize(50, 50))
        self.label44.setFrameShape(QtWidgets.QFrame.Box)
        self.label44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label44.setLineWidth(1)
        self.label44.setText("")
        self.label44.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label44.setScaledContents(True)
        self.label44.setObjectName("label44")
        self.blankgrid.addWidget(self.label44, 3, 3, 1, 1)
        self.label54 = QtWidgets.QLabel(self.centralwidget)
        self.label54.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label54.sizePolicy().hasHeightForWidth())
        self.label54.setSizePolicy(sizePolicy)
        self.label54.setMinimumSize(QtCore.QSize(50, 50))
        self.label54.setSizeIncrement(QtCore.QSize(1, 1))
        self.label54.setBaseSize(QtCore.QSize(50, 50))
        self.label54.setFrameShape(QtWidgets.QFrame.Box)
        self.label54.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label54.setLineWidth(1)
        self.label54.setText("")
        self.label54.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label54.setScaledContents(True)
        self.label54.setObjectName("label54")
        self.blankgrid.addWidget(self.label54, 3, 4, 1, 1)
        self.label31 = QtWidgets.QLabel(self.centralwidget)
        self.label31.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label31.sizePolicy().hasHeightForWidth())
        self.label31.setSizePolicy(sizePolicy)
        self.label31.setMinimumSize(QtCore.QSize(50, 50))
        self.label31.setSizeIncrement(QtCore.QSize(1, 1))
        self.label31.setBaseSize(QtCore.QSize(50, 50))
        self.label31.setFrameShape(QtWidgets.QFrame.Box)
        self.label31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label31.setLineWidth(1)
        self.label31.setText("")
        self.label31.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label31.setScaledContents(True)
        self.label31.setObjectName("label31")
        self.blankgrid.addWidget(self.label31, 0, 2, 1, 1)
        self.label11 = QtWidgets.QLabel(self.centralwidget)
        self.label11.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label11.sizePolicy().hasHeightForWidth())
        self.label11.setSizePolicy(sizePolicy)
        self.label11.setMinimumSize(QtCore.QSize(50, 50))
        self.label11.setSizeIncrement(QtCore.QSize(1, 1))
        self.label11.setBaseSize(QtCore.QSize(50, 50))
        self.label11.setFrameShape(QtWidgets.QFrame.Box)
        self.label11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label11.setLineWidth(1)
        self.label11.setText("")
        self.label11.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label11.setScaledContents(True)
        self.label11.setObjectName("label11")
        self.blankgrid.addWidget(self.label11, 0, 0, 1, 1)
        self.label51 = QtWidgets.QLabel(self.centralwidget)
        self.label51.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label51.sizePolicy().hasHeightForWidth())
        self.label51.setSizePolicy(sizePolicy)
        self.label51.setMinimumSize(QtCore.QSize(50, 50))
        self.label51.setSizeIncrement(QtCore.QSize(1, 1))
        self.label51.setBaseSize(QtCore.QSize(50, 50))
        self.label51.setFrameShape(QtWidgets.QFrame.Box)
        self.label51.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label51.setLineWidth(1)
        self.label51.setText("")
        self.label51.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label51.setScaledContents(True)
        self.label51.setObjectName("label51")
        self.blankgrid.addWidget(self.label51, 0, 4, 1, 1)
        self.label12 = QtWidgets.QLabel(self.centralwidget)
        self.label12.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label12.sizePolicy().hasHeightForWidth())
        self.label12.setSizePolicy(sizePolicy)
        self.label12.setMinimumSize(QtCore.QSize(50, 50))
        self.label12.setSizeIncrement(QtCore.QSize(1, 1))
        self.label12.setBaseSize(QtCore.QSize(50, 50))
        self.label12.setFrameShape(QtWidgets.QFrame.Box)
        self.label12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label12.setLineWidth(1)
        self.label12.setText("")
        self.label12.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label12.setScaledContents(True)
        self.label12.setObjectName("label12")
        self.blankgrid.addWidget(self.label12, 1, 0, 1, 1)
        self.label52 = QtWidgets.QLabel(self.centralwidget)
        self.label52.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label52.sizePolicy().hasHeightForWidth())
        self.label52.setSizePolicy(sizePolicy)
        self.label52.setMinimumSize(QtCore.QSize(50, 50))
        self.label52.setSizeIncrement(QtCore.QSize(1, 1))
        self.label52.setBaseSize(QtCore.QSize(50, 50))
        self.label52.setFrameShape(QtWidgets.QFrame.Box)
        self.label52.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label52.setLineWidth(1)
        self.label52.setText("")
        self.label52.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label52.setScaledContents(True)
        self.label52.setObjectName("label52")
        self.blankgrid.addWidget(self.label52, 1, 4, 1, 1)
        self.label53 = QtWidgets.QLabel(self.centralwidget)
        self.label53.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label53.sizePolicy().hasHeightForWidth())
        self.label53.setSizePolicy(sizePolicy)
        self.label53.setMinimumSize(QtCore.QSize(50, 50))
        self.label53.setSizeIncrement(QtCore.QSize(1, 1))
        self.label53.setBaseSize(QtCore.QSize(50, 50))
        self.label53.setFrameShape(QtWidgets.QFrame.Box)
        self.label53.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label53.setLineWidth(1)
        self.label53.setText("")
        self.label53.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label53.setScaledContents(True)
        self.label53.setObjectName("label53")
        self.blankgrid.addWidget(self.label53, 2, 4, 1, 1)
        self.label32 = QtWidgets.QLabel(self.centralwidget)
        self.label32.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label32.sizePolicy().hasHeightForWidth())
        self.label32.setSizePolicy(sizePolicy)
        self.label32.setMinimumSize(QtCore.QSize(50, 50))
        self.label32.setSizeIncrement(QtCore.QSize(1, 1))
        self.label32.setBaseSize(QtCore.QSize(50, 50))
        self.label32.setFrameShape(QtWidgets.QFrame.Box)
        self.label32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label32.setLineWidth(1)
        self.label32.setText("")
        self.label32.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label32.setScaledContents(True)
        self.label32.setObjectName("label32")
        self.blankgrid.addWidget(self.label32, 1, 2, 1, 1)
        self.label35 = QtWidgets.QLabel(self.centralwidget)
        self.label35.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label35.sizePolicy().hasHeightForWidth())
        self.label35.setSizePolicy(sizePolicy)
        self.label35.setMinimumSize(QtCore.QSize(50, 50))
        self.label35.setSizeIncrement(QtCore.QSize(1, 1))
        self.label35.setBaseSize(QtCore.QSize(50, 50))
        self.label35.setFrameShape(QtWidgets.QFrame.Box)
        self.label35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label35.setLineWidth(1)
        self.label35.setText("")
        self.label35.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label35.setScaledContents(True)
        self.label35.setObjectName("label35")
        self.blankgrid.addWidget(self.label35, 4, 2, 1, 1)
        self.label23 = QtWidgets.QLabel(self.centralwidget)
        self.label23.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label23.sizePolicy().hasHeightForWidth())
        self.label23.setSizePolicy(sizePolicy)
        self.label23.setMinimumSize(QtCore.QSize(50, 50))
        self.label23.setSizeIncrement(QtCore.QSize(1, 1))
        self.label23.setBaseSize(QtCore.QSize(50, 50))
        self.label23.setFrameShape(QtWidgets.QFrame.Box)
        self.label23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label23.setLineWidth(1)
        self.label23.setText("")
        self.label23.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label23.setScaledContents(True)
        self.label23.setObjectName("label23")
        self.blankgrid.addWidget(self.label23, 2, 1, 1, 1)
        self.label45 = QtWidgets.QLabel(self.centralwidget)
        self.label45.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label45.sizePolicy().hasHeightForWidth())
        self.label45.setSizePolicy(sizePolicy)
        self.label45.setMinimumSize(QtCore.QSize(50, 50))
        self.label45.setSizeIncrement(QtCore.QSize(1, 1))
        self.label45.setBaseSize(QtCore.QSize(50, 50))
        self.label45.setFrameShape(QtWidgets.QFrame.Box)
        self.label45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label45.setLineWidth(1)
        self.label45.setText("")
        self.label45.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label45.setScaledContents(True)
        self.label45.setObjectName("label45")
        self.blankgrid.addWidget(self.label45, 4, 3, 1, 1)
        self.label13 = QtWidgets.QLabel(self.centralwidget)
        self.label13.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label13.sizePolicy().hasHeightForWidth())
        self.label13.setSizePolicy(sizePolicy)
        self.label13.setMinimumSize(QtCore.QSize(50, 50))
        self.label13.setSizeIncrement(QtCore.QSize(1, 1))
        self.label13.setBaseSize(QtCore.QSize(50, 50))
        self.label13.setFrameShape(QtWidgets.QFrame.Box)
        self.label13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label13.setLineWidth(1)
        self.label13.setText("")
        self.label13.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label13.setScaledContents(True)
        self.label13.setObjectName("label13")
        self.blankgrid.addWidget(self.label13, 2, 0, 1, 1)
        self.label43 = QtWidgets.QLabel(self.centralwidget)
        self.label43.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label43.sizePolicy().hasHeightForWidth())
        self.label43.setSizePolicy(sizePolicy)
        self.label43.setMinimumSize(QtCore.QSize(50, 50))
        self.label43.setSizeIncrement(QtCore.QSize(1, 1))
        self.label43.setBaseSize(QtCore.QSize(50, 50))
        self.label43.setFrameShape(QtWidgets.QFrame.Box)
        self.label43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label43.setLineWidth(1)
        self.label43.setText("")
        self.label43.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label43.setScaledContents(True)
        self.label43.setObjectName("label43")
        self.blankgrid.addWidget(self.label43, 2, 3, 1, 1)
        self.label14 = QtWidgets.QLabel(self.centralwidget)
        self.label14.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label14.sizePolicy().hasHeightForWidth())
        self.label14.setSizePolicy(sizePolicy)
        self.label14.setMinimumSize(QtCore.QSize(50, 50))
        self.label14.setSizeIncrement(QtCore.QSize(1, 1))
        self.label14.setBaseSize(QtCore.QSize(50, 50))
        self.label14.setFrameShape(QtWidgets.QFrame.Box)
        self.label14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label14.setLineWidth(1)
        self.label14.setText("")
        self.label14.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label14.setScaledContents(True)
        self.label14.setObjectName("label14")
        self.blankgrid.addWidget(self.label14, 3, 0, 1, 1)
        self.label22 = QtWidgets.QLabel(self.centralwidget)
        self.label22.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label22.sizePolicy().hasHeightForWidth())
        self.label22.setSizePolicy(sizePolicy)
        self.label22.setMinimumSize(QtCore.QSize(50, 50))
        self.label22.setSizeIncrement(QtCore.QSize(1, 1))
        self.label22.setBaseSize(QtCore.QSize(50, 50))
        self.label22.setFrameShape(QtWidgets.QFrame.Box)
        self.label22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label22.setLineWidth(1)
        self.label22.setText("")
        self.label22.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label22.setScaledContents(True)
        self.label22.setObjectName("label22")
        self.blankgrid.addWidget(self.label22, 1, 1, 1, 1)
        self.label24 = QtWidgets.QLabel(self.centralwidget)
        self.label24.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label24.sizePolicy().hasHeightForWidth())
        self.label24.setSizePolicy(sizePolicy)
        self.label24.setMinimumSize(QtCore.QSize(50, 50))
        self.label24.setSizeIncrement(QtCore.QSize(1, 1))
        self.label24.setBaseSize(QtCore.QSize(50, 50))
        self.label24.setFrameShape(QtWidgets.QFrame.Box)
        self.label24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label24.setLineWidth(1)
        self.label24.setText("")
        self.label24.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label24.setScaledContents(True)
        self.label24.setObjectName("label24")
        self.blankgrid.addWidget(self.label24, 3, 1, 1, 1)
        self.label33 = QtWidgets.QLabel(self.centralwidget)
        self.label33.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label33.sizePolicy().hasHeightForWidth())
        self.label33.setSizePolicy(sizePolicy)
        self.label33.setMinimumSize(QtCore.QSize(50, 50))
        self.label33.setSizeIncrement(QtCore.QSize(1, 1))
        self.label33.setBaseSize(QtCore.QSize(50, 50))
        self.label33.setFrameShape(QtWidgets.QFrame.Box)
        self.label33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label33.setLineWidth(1)
        self.label33.setText("")
        self.label33.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label33.setScaledContents(True)
        self.label33.setObjectName("label33")
        self.blankgrid.addWidget(self.label33, 2, 2, 1, 1)
        self.label55 = QtWidgets.QLabel(self.centralwidget)
        self.label55.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label55.sizePolicy().hasHeightForWidth())
        self.label55.setSizePolicy(sizePolicy)
        self.label55.setMinimumSize(QtCore.QSize(50, 50))
        self.label55.setSizeIncrement(QtCore.QSize(1, 1))
        self.label55.setBaseSize(QtCore.QSize(50, 50))
        self.label55.setFrameShape(QtWidgets.QFrame.Box)
        self.label55.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label55.setLineWidth(1)
        self.label55.setText("")
        self.label55.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label55.setScaledContents(True)
        self.label55.setObjectName("label55")
        self.blankgrid.addWidget(self.label55, 4, 4, 1, 1)
        self.label42 = QtWidgets.QLabel(self.centralwidget)
        self.label42.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label42.sizePolicy().hasHeightForWidth())
        self.label42.setSizePolicy(sizePolicy)
        self.label42.setMinimumSize(QtCore.QSize(50, 50))
        self.label42.setSizeIncrement(QtCore.QSize(1, 1))
        self.label42.setBaseSize(QtCore.QSize(50, 50))
        self.label42.setFrameShape(QtWidgets.QFrame.Box)
        self.label42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label42.setLineWidth(1)
        self.label42.setText("")
        self.label42.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label42.setScaledContents(True)
        self.label42.setObjectName("label42")
        self.blankgrid.addWidget(self.label42, 1, 3, 1, 1)
        self.label15 = QtWidgets.QLabel(self.centralwidget)
        self.label15.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label15.sizePolicy().hasHeightForWidth())
        self.label15.setSizePolicy(sizePolicy)
        self.label15.setMinimumSize(QtCore.QSize(50, 50))
        self.label15.setSizeIncrement(QtCore.QSize(1, 1))
        self.label15.setBaseSize(QtCore.QSize(50, 50))
        self.label15.setFrameShape(QtWidgets.QFrame.Box)
        self.label15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label15.setLineWidth(1)
        self.label15.setText("")
        self.label15.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label15.setScaledContents(True)
        self.label15.setObjectName("label15")
        self.blankgrid.addWidget(self.label15, 4, 0, 1, 1)
        self.label25 = QtWidgets.QLabel(self.centralwidget)
        self.label25.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label25.sizePolicy().hasHeightForWidth())
        self.label25.setSizePolicy(sizePolicy)
        self.label25.setMinimumSize(QtCore.QSize(50, 50))
        self.label25.setSizeIncrement(QtCore.QSize(1, 1))
        self.label25.setBaseSize(QtCore.QSize(50, 50))
        self.label25.setFrameShape(QtWidgets.QFrame.Box)
        self.label25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label25.setLineWidth(1)
        self.label25.setText("")
        self.label25.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label25.setScaledContents(True)
        self.label25.setObjectName("label25")
        self.blankgrid.addWidget(self.label25, 4, 1, 1, 1)
        self.maingrid.addLayout(self.blankgrid, 1, 0, 1, 1)
        self.messagetextedit = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        self.messagetextedit.setFont(font)
        self.messagetextedit.setReadOnly(True)
        self.messagetextedit.setObjectName("messagetextedit")
        self.maingrid.addWidget(self.messagetextedit, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.maingrid, 8, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FLR"))
        self.NButton.setText(_translate("MainWindow", "N"))
        self.LBracketButton.setText(_translate("MainWindow", "("))
        self.N1Button.setText(_translate("MainWindow", "1"))
        self.EqualButton.setText(_translate("MainWindow", "="))
        self.UButton.setText(_translate("MainWindow", "U"))
        self.FButton.setText(_translate("MainWindow", "F"))
        self.RBracketButton.setText(_translate("MainWindow", ")"))
        self.LMBracketButton.setText(_translate("MainWindow", "["))
        self.NewlineButton.setText(_translate("MainWindow", "|"))
        self.BackspaceButton.setText(_translate("MainWindow", "<-"))
        self.N2Button.setText(_translate("MainWindow", "2"))
        self.N3Button.setText(_translate("MainWindow", "3"))
        self.N4Button.setText(_translate("MainWindow", "4"))
        self.N5Button.setText(_translate("MainWindow", "5"))
        self.RMBracketButton.setText(_translate("MainWindow", "]"))
        self.SButton.setText(_translate("MainWindow", "S"))
        self.LButton.setText(_translate("MainWindow", "L"))
        self.RunButton.setText(_translate("MainWindow", "RUN"))
        self.StopButton.setText(_translate("MainWindow", "STOP"))
        self.BButton.setText(_translate("MainWindow", "B"))
        self.RButton.setText(_translate("MainWindow", "R"))
        self.IfButton.setText(_translate("MainWindow", "IF"))
        self.ElseButton.setText(_translate("MainWindow", "ELSE"))
        self.WhileButton.setText(_translate("MainWindow", "WHILE"))

