# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maindesign.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2053, 1470)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FButton = QtWidgets.QPushButton(self.centralwidget)
        self.FButton.setGeometry(QtCore.QRect(10, 890, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.FButton.setFont(font)
        self.FButton.setObjectName("FButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(910, 30, 1121, 821))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 670, 150, 150))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("res/up.png"))
        self.label.setObjectName("label")
        self.LButton = QtWidgets.QPushButton(self.centralwidget)
        self.LButton.setGeometry(QtCore.QRect(150, 890, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.LButton.setFont(font)
        self.LButton.setObjectName("LButton")
        self.RButton = QtWidgets.QPushButton(self.centralwidget)
        self.RButton.setGeometry(QtCore.QRect(290, 890, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.RButton.setFont(font)
        self.RButton.setObjectName("RButton")
        self.LBracketButton = QtWidgets.QPushButton(self.centralwidget)
        self.LBracketButton.setGeometry(QtCore.QRect(430, 890, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.LBracketButton.setFont(font)
        self.LBracketButton.setObjectName("LBracketButton")
        self.RBracketButton = QtWidgets.QPushButton(self.centralwidget)
        self.RBracketButton.setGeometry(QtCore.QRect(570, 890, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.RBracketButton.setFont(font)
        self.RBracketButton.setObjectName("RBracketButton")
        self.N1Button = QtWidgets.QPushButton(self.centralwidget)
        self.N1Button.setGeometry(QtCore.QRect(910, 890, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.N1Button.setFont(font)
        self.N1Button.setObjectName("N1Button")
        self.N3Button = QtWidgets.QPushButton(self.centralwidget)
        self.N3Button.setGeometry(QtCore.QRect(1190, 890, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.N3Button.setFont(font)
        self.N3Button.setObjectName("N3Button")
        self.N5Button = QtWidgets.QPushButton(self.centralwidget)
        self.N5Button.setGeometry(QtCore.QRect(1470, 890, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.N5Button.setFont(font)
        self.N5Button.setObjectName("N5Button")
        self.N4Button = QtWidgets.QPushButton(self.centralwidget)
        self.N4Button.setGeometry(QtCore.QRect(1330, 890, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.N4Button.setFont(font)
        self.N4Button.setObjectName("N4Button")
        self.N2Button = QtWidgets.QPushButton(self.centralwidget)
        self.N2Button.setGeometry(QtCore.QRect(1050, 890, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.N2Button.setFont(font)
        self.N2Button.setObjectName("N2Button")
        self.BackspaceButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackspaceButton.setGeometry(QtCore.QRect(1680, 890, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.BackspaceButton.setFont(font)
        self.BackspaceButton.setObjectName("BackspaceButton")
        self.RunButton = QtWidgets.QPushButton(self.centralwidget)
        self.RunButton.setGeometry(QtCore.QRect(780, 890, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.RunButton.setFont(font)
        self.RunButton.setObjectName("RunButton")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(650, 70, 150, 150))
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(350, 220, 150, 150))
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(650, 220, 150, 150))
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(500, 220, 150, 150))
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(50, 220, 150, 150))
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(200, 220, 150, 150))
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(350, 370, 150, 150))
        self.label_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(650, 520, 150, 150))
        self.label_13.setFrameShape(QtWidgets.QFrame.Box)
        self.label_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(200, 520, 150, 150))
        self.label_14.setFrameShape(QtWidgets.QFrame.Box)
        self.label_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(650, 370, 150, 150))
        self.label_15.setFrameShape(QtWidgets.QFrame.Box)
        self.label_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(500, 520, 150, 150))
        self.label_16.setFrameShape(QtWidgets.QFrame.Box)
        self.label_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(500, 370, 150, 150))
        self.label_17.setFrameShape(QtWidgets.QFrame.Box)
        self.label_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(50, 370, 150, 150))
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(200, 370, 150, 150))
        self.label_19.setFrameShape(QtWidgets.QFrame.Box)
        self.label_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(50, 520, 150, 150))
        self.label_20.setFrameShape(QtWidgets.QFrame.Box)
        self.label_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(350, 520, 150, 150))
        self.label_21.setFrameShape(QtWidgets.QFrame.Box)
        self.label_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(200, 670, 150, 150))
        self.label_22.setFrameShape(QtWidgets.QFrame.Box)
        self.label_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(50, 670, 150, 150))
        self.label_23.setFrameShape(QtWidgets.QFrame.Box)
        self.label_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(350, 670, 150, 150))
        self.label_24.setFrameShape(QtWidgets.QFrame.Box)
        self.label_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(500, 670, 150, 150))
        self.label_25.setFrameShape(QtWidgets.QFrame.Box)
        self.label_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(650, 670, 150, 150))
        self.label_26.setFrameShape(QtWidgets.QFrame.Box)
        self.label_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_26.setObjectName("label_26")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(350, 70, 150, 150))
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(500, 70, 150, 150))
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 150, 150))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 70, 150, 150))
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label_3.setObjectName("label_3")
        self.FButton.raise_()
        self.textEdit.raise_()
        self.LButton.raise_()
        self.RButton.raise_()
        self.LBracketButton.raise_()
        self.RBracketButton.raise_()
        self.N1Button.raise_()
        self.N3Button.raise_()
        self.N5Button.raise_()
        self.N4Button.raise_()
        self.N2Button.raise_()
        self.BackspaceButton.raise_()
        self.RunButton.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2053, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FButton.setText(_translate("MainWindow", "F"))
        self.LButton.setText(_translate("MainWindow", "L"))
        self.RButton.setText(_translate("MainWindow", "R"))
        self.LBracketButton.setText(_translate("MainWindow", "("))
        self.RBracketButton.setText(_translate("MainWindow", ")"))
        self.N1Button.setText(_translate("MainWindow", "1"))
        self.N3Button.setText(_translate("MainWindow", "3"))
        self.N5Button.setText(_translate("MainWindow", "5"))
        self.N4Button.setText(_translate("MainWindow", "4"))
        self.N2Button.setText(_translate("MainWindow", "2"))
        self.BackspaceButton.setText(_translate("MainWindow", "<-"))
        self.RunButton.setText(_translate("MainWindow", "RUN"))

