# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maindesign.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2053, 1470)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FButton = QtWidgets.QPushButton(self.centralwidget)
        self.FButton.setGeometry(QtCore.QRect(910, 1030, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.FButton.setFont(font)
        self.FButton.setObjectName("FButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(910, 30, 1121, 821))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.aeroplane_label = QtWidgets.QLabel(self.centralwidget)
        self.aeroplane_label.setGeometry(QtCore.QRect(60, 640, 131, 121))
        self.aeroplane_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.aeroplane_label.setText("")
        self.aeroplane_label.setPixmap(QtGui.QPixmap("res/UP.png"))
        self.aeroplane_label.setObjectName("aeroplane_label")
        self.LButton = QtWidgets.QPushButton(self.centralwidget)
        self.LButton.setGeometry(QtCore.QRect(1050, 1030, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.LButton.setFont(font)
        self.LButton.setObjectName("LButton")
        self.RButton = QtWidgets.QPushButton(self.centralwidget)
        self.RButton.setGeometry(QtCore.QRect(1190, 1030, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.RButton.setFont(font)
        self.RButton.setObjectName("RButton")
        self.LBracketButton = QtWidgets.QPushButton(self.centralwidget)
        self.LBracketButton.setGeometry(QtCore.QRect(1470, 1030, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.LBracketButton.setFont(font)
        self.LBracketButton.setObjectName("LBracketButton")
        self.RBracketButton = QtWidgets.QPushButton(self.centralwidget)
        self.RBracketButton.setGeometry(QtCore.QRect(1610, 1030, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.RBracketButton.setFont(font)
        self.RBracketButton.setObjectName("RBracketButton")
        self.N1Button = QtWidgets.QPushButton(self.centralwidget)
        self.N1Button.setGeometry(QtCore.QRect(910, 890, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.N1Button.setFont(font)
        self.N1Button.setObjectName("N1Button")
        self.N3Button = QtWidgets.QPushButton(self.centralwidget)
        self.N3Button.setGeometry(QtCore.QRect(1190, 890, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.N3Button.setFont(font)
        self.N3Button.setObjectName("N3Button")
        self.N5Button = QtWidgets.QPushButton(self.centralwidget)
        self.N5Button.setGeometry(QtCore.QRect(1470, 890, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.N5Button.setFont(font)
        self.N5Button.setObjectName("N5Button")
        self.N4Button = QtWidgets.QPushButton(self.centralwidget)
        self.N4Button.setGeometry(QtCore.QRect(1330, 890, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.N4Button.setFont(font)
        self.N4Button.setObjectName("N4Button")
        self.N2Button = QtWidgets.QPushButton(self.centralwidget)
        self.N2Button.setGeometry(QtCore.QRect(1050, 890, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.N2Button.setFont(font)
        self.N2Button.setObjectName("N2Button")
        self.BackspaceButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackspaceButton.setGeometry(QtCore.QRect(1610, 890, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.BackspaceButton.setFont(font)
        self.BackspaceButton.setObjectName("BackspaceButton")
        self.RunButton = QtWidgets.QPushButton(self.centralwidget)
        self.RunButton.setGeometry(QtCore.QRect(1850, 1030, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.RunButton.setFont(font)
        self.RunButton.setAutoFillBackground(False)
        self.RunButton.setObjectName("RunButton")
        self.label51 = QtWidgets.QLabel(self.centralwidget)
        self.label51.setGeometry(QtCore.QRect(650, 30, 150, 150))
        self.label51.setFrameShape(QtWidgets.QFrame.Box)
        self.label51.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label51.setText("")
        self.label51.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label51.setObjectName("label51")
        self.label32 = QtWidgets.QLabel(self.centralwidget)
        self.label32.setGeometry(QtCore.QRect(350, 180, 150, 150))
        self.label32.setFrameShape(QtWidgets.QFrame.Box)
        self.label32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label32.setText("")
        self.label32.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label32.setObjectName("label32")
        self.label52 = QtWidgets.QLabel(self.centralwidget)
        self.label52.setGeometry(QtCore.QRect(650, 180, 150, 150))
        self.label52.setFrameShape(QtWidgets.QFrame.Box)
        self.label52.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label52.setText("")
        self.label52.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label52.setObjectName("label52")
        self.label42 = QtWidgets.QLabel(self.centralwidget)
        self.label42.setGeometry(QtCore.QRect(500, 180, 150, 150))
        self.label42.setFrameShape(QtWidgets.QFrame.Box)
        self.label42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label42.setText("")
        self.label42.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label42.setObjectName("label42")
        self.label12 = QtWidgets.QLabel(self.centralwidget)
        self.label12.setGeometry(QtCore.QRect(50, 180, 150, 150))
        self.label12.setFrameShape(QtWidgets.QFrame.Box)
        self.label12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label12.setText("")
        self.label12.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label12.setObjectName("label12")
        self.label22 = QtWidgets.QLabel(self.centralwidget)
        self.label22.setGeometry(QtCore.QRect(200, 180, 150, 150))
        self.label22.setFrameShape(QtWidgets.QFrame.Box)
        self.label22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label22.setText("")
        self.label22.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label22.setObjectName("label22")
        self.label33 = QtWidgets.QLabel(self.centralwidget)
        self.label33.setGeometry(QtCore.QRect(350, 330, 150, 150))
        self.label33.setFrameShape(QtWidgets.QFrame.Box)
        self.label33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label33.setText("")
        self.label33.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label33.setObjectName("label33")
        self.label54 = QtWidgets.QLabel(self.centralwidget)
        self.label54.setGeometry(QtCore.QRect(650, 480, 150, 150))
        self.label54.setFrameShape(QtWidgets.QFrame.Box)
        self.label54.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label54.setText("")
        self.label54.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label54.setObjectName("label54")
        self.label24 = QtWidgets.QLabel(self.centralwidget)
        self.label24.setGeometry(QtCore.QRect(200, 480, 150, 150))
        self.label24.setFrameShape(QtWidgets.QFrame.Box)
        self.label24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label24.setText("")
        self.label24.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label24.setObjectName("label24")
        self.label53 = QtWidgets.QLabel(self.centralwidget)
        self.label53.setGeometry(QtCore.QRect(650, 330, 150, 150))
        self.label53.setFrameShape(QtWidgets.QFrame.Box)
        self.label53.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label53.setText("")
        self.label53.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label53.setObjectName("label53")
        self.label44 = QtWidgets.QLabel(self.centralwidget)
        self.label44.setGeometry(QtCore.QRect(500, 480, 150, 150))
        self.label44.setFrameShape(QtWidgets.QFrame.Box)
        self.label44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label44.setText("")
        self.label44.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label44.setObjectName("label44")
        self.label43 = QtWidgets.QLabel(self.centralwidget)
        self.label43.setGeometry(QtCore.QRect(500, 330, 150, 150))
        self.label43.setFrameShape(QtWidgets.QFrame.Box)
        self.label43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label43.setText("")
        self.label43.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label43.setObjectName("label43")
        self.label13 = QtWidgets.QLabel(self.centralwidget)
        self.label13.setGeometry(QtCore.QRect(50, 330, 150, 150))
        self.label13.setFrameShape(QtWidgets.QFrame.Box)
        self.label13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label13.setText("")
        self.label13.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label13.setObjectName("label13")
        self.label23 = QtWidgets.QLabel(self.centralwidget)
        self.label23.setGeometry(QtCore.QRect(200, 330, 150, 150))
        self.label23.setFrameShape(QtWidgets.QFrame.Box)
        self.label23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label23.setText("")
        self.label23.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label23.setObjectName("label23")
        self.label14 = QtWidgets.QLabel(self.centralwidget)
        self.label14.setGeometry(QtCore.QRect(50, 480, 150, 150))
        self.label14.setFrameShape(QtWidgets.QFrame.Box)
        self.label14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label14.setText("")
        self.label14.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label14.setObjectName("label14")
        self.label34 = QtWidgets.QLabel(self.centralwidget)
        self.label34.setGeometry(QtCore.QRect(350, 480, 150, 150))
        self.label34.setFrameShape(QtWidgets.QFrame.Box)
        self.label34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label34.setText("")
        self.label34.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label34.setObjectName("label34")
        self.label25 = QtWidgets.QLabel(self.centralwidget)
        self.label25.setGeometry(QtCore.QRect(200, 630, 150, 150))
        self.label25.setFrameShape(QtWidgets.QFrame.Box)
        self.label25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label25.setText("")
        self.label25.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label25.setObjectName("label25")
        self.label15 = QtWidgets.QLabel(self.centralwidget)
        self.label15.setGeometry(QtCore.QRect(50, 630, 150, 150))
        self.label15.setFrameShape(QtWidgets.QFrame.Box)
        self.label15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label15.setText("")
        self.label15.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label15.setObjectName("label15")
        self.label35 = QtWidgets.QLabel(self.centralwidget)
        self.label35.setGeometry(QtCore.QRect(350, 630, 150, 150))
        self.label35.setFrameShape(QtWidgets.QFrame.Box)
        self.label35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label35.setText("")
        self.label35.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label35.setObjectName("label35")
        self.label45 = QtWidgets.QLabel(self.centralwidget)
        self.label45.setGeometry(QtCore.QRect(500, 630, 150, 150))
        self.label45.setFrameShape(QtWidgets.QFrame.Box)
        self.label45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label45.setText("")
        self.label45.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label45.setObjectName("label45")
        self.label55 = QtWidgets.QLabel(self.centralwidget)
        self.label55.setGeometry(QtCore.QRect(650, 630, 150, 150))
        self.label55.setFrameShape(QtWidgets.QFrame.Box)
        self.label55.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label55.setText("")
        self.label55.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label55.setObjectName("label55")
        self.label31 = QtWidgets.QLabel(self.centralwidget)
        self.label31.setGeometry(QtCore.QRect(350, 30, 150, 150))
        self.label31.setFrameShape(QtWidgets.QFrame.Box)
        self.label31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label31.setText("")
        self.label31.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label31.setObjectName("label31")
        self.label41 = QtWidgets.QLabel(self.centralwidget)
        self.label41.setGeometry(QtCore.QRect(500, 30, 150, 150))
        self.label41.setFrameShape(QtWidgets.QFrame.Box)
        self.label41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label41.setText("")
        self.label41.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label41.setObjectName("label41")
        self.label11 = QtWidgets.QLabel(self.centralwidget)
        self.label11.setGeometry(QtCore.QRect(50, 30, 150, 150))
        self.label11.setFrameShape(QtWidgets.QFrame.Box)
        self.label11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label11.setText("")
        self.label11.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label11.setObjectName("label11")
        self.label21 = QtWidgets.QLabel(self.centralwidget)
        self.label21.setGeometry(QtCore.QRect(200, 30, 150, 150))
        self.label21.setFrameShape(QtWidgets.QFrame.Box)
        self.label21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label21.setText("")
        self.label21.setPixmap(QtGui.QPixmap("res/blank.png"))
        self.label21.setObjectName("label21")
        self.RMBracketButton = QtWidgets.QPushButton(self.centralwidget)
        self.RMBracketButton.setGeometry(QtCore.QRect(1610, 1160, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.RMBracketButton.setFont(font)
        self.RMBracketButton.setObjectName("RMBracketButton")
        self.LMBracketButton = QtWidgets.QPushButton(self.centralwidget)
        self.LMBracketButton.setGeometry(QtCore.QRect(1470, 1160, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.LMBracketButton.setFont(font)
        self.LMBracketButton.setObjectName("LMBracketButton")
        self.BButton = QtWidgets.QPushButton(self.centralwidget)
        self.BButton.setGeometry(QtCore.QRect(1330, 1030, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.BButton.setFont(font)
        self.BButton.setObjectName("BButton")
        self.NButton = QtWidgets.QPushButton(self.centralwidget)
        self.NButton.setGeometry(QtCore.QRect(910, 1160, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.NButton.setFont(font)
        self.NButton.setObjectName("NButton")
        self.SButton = QtWidgets.QPushButton(self.centralwidget)
        self.SButton.setGeometry(QtCore.QRect(1050, 1160, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.SButton.setFont(font)
        self.SButton.setObjectName("SButton")
        self.ClearButton = QtWidgets.QPushButton(self.centralwidget)
        self.ClearButton.setGeometry(QtCore.QRect(60, 880, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.ClearButton.setFont(font)
        self.ClearButton.setObjectName("ClearButton")
        self.StopButton = QtWidgets.QPushButton(self.centralwidget)
        self.StopButton.setGeometry(QtCore.QRect(1850, 1160, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.StopButton.setFont(font)
        self.StopButton.setAutoFillBackground(False)
        self.StopButton.setObjectName("StopButton")
        self.IfButton = QtWidgets.QPushButton(self.centralwidget)
        self.IfButton.setGeometry(QtCore.QRect(910, 1280, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.IfButton.setFont(font)
        self.IfButton.setObjectName("IfButton")
        self.WhileButton = QtWidgets.QPushButton(self.centralwidget)
        self.WhileButton.setGeometry(QtCore.QRect(1260, 1280, 201, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.WhileButton.setFont(font)
        self.WhileButton.setObjectName("WhileButton")
        self.UButton = QtWidgets.QPushButton(self.centralwidget)
        self.UButton.setGeometry(QtCore.QRect(1190, 1160, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.UButton.setFont(font)
        self.UButton.setObjectName("UButton")
        self.ElseButton = QtWidgets.QPushButton(self.centralwidget)
        self.ElseButton.setGeometry(QtCore.QRect(1050, 1280, 201, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.ElseButton.setFont(font)
        self.ElseButton.setObjectName("ElseButton")
        self.NewlineButton = QtWidgets.QPushButton(self.centralwidget)
        self.NewlineButton.setGeometry(QtCore.QRect(1850, 890, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.NewlineButton.setFont(font)
        self.NewlineButton.setObjectName("NewlineButton")
        self.EqualButton = QtWidgets.QPushButton(self.centralwidget)
        self.EqualButton.setGeometry(QtCore.QRect(1330, 1160, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        self.EqualButton.setFont(font)
        self.EqualButton.setObjectName("EqualButton")
        self.FButton.raise_()
        self.textEdit.raise_()
        self.LButton.raise_()
        self.RButton.raise_()
        self.LBracketButton.raise_()
        self.RBracketButton.raise_()
        self.N1Button.raise_()
        self.N3Button.raise_()
        self.N5Button.raise_()
        self.N4Button.raise_()
        self.N2Button.raise_()
        self.BackspaceButton.raise_()
        self.RunButton.raise_()
        self.label41.raise_()
        self.label31.raise_()
        self.label21.raise_()
        self.label11.raise_()
        self.label51.raise_()
        self.label32.raise_()
        self.label52.raise_()
        self.label42.raise_()
        self.label12.raise_()
        self.label22.raise_()
        self.label33.raise_()
        self.label54.raise_()
        self.label24.raise_()
        self.label53.raise_()
        self.label44.raise_()
        self.label43.raise_()
        self.label13.raise_()
        self.label23.raise_()
        self.label14.raise_()
        self.label34.raise_()
        self.label25.raise_()
        self.label15.raise_()
        self.label35.raise_()
        self.label45.raise_()
        self.label55.raise_()
        self.aeroplane_label.raise_()
        self.RMBracketButton.raise_()
        self.LMBracketButton.raise_()
        self.BButton.raise_()
        self.NButton.raise_()
        self.SButton.raise_()
        self.ClearButton.raise_()
        self.StopButton.raise_()
        self.IfButton.raise_()
        self.WhileButton.raise_()
        self.UButton.raise_()
        self.ElseButton.raise_()
        self.NewlineButton.raise_()
        self.EqualButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2053, 38))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FButton.setText(_translate("MainWindow", "F"))
        self.LButton.setText(_translate("MainWindow", "L"))
        self.RButton.setText(_translate("MainWindow", "R"))
        self.LBracketButton.setText(_translate("MainWindow", "("))
        self.RBracketButton.setText(_translate("MainWindow", ")"))
        self.N1Button.setText(_translate("MainWindow", "1"))
        self.N3Button.setText(_translate("MainWindow", "3"))
        self.N5Button.setText(_translate("MainWindow", "5"))
        self.N4Button.setText(_translate("MainWindow", "4"))
        self.N2Button.setText(_translate("MainWindow", "2"))
        self.BackspaceButton.setText(_translate("MainWindow", "<-"))
        self.RunButton.setText(_translate("MainWindow", "RUN"))
        self.RMBracketButton.setText(_translate("MainWindow", "]"))
        self.LMBracketButton.setText(_translate("MainWindow", "["))
        self.BButton.setText(_translate("MainWindow", "B"))
        self.NButton.setText(_translate("MainWindow", "N"))
        self.SButton.setText(_translate("MainWindow", "S"))
        self.ClearButton.setText(_translate("MainWindow", "Clr"))
        self.StopButton.setText(_translate("MainWindow", "STOP"))
        self.IfButton.setText(_translate("MainWindow", "IF"))
        self.WhileButton.setText(_translate("MainWindow", "WHILE"))
        self.UButton.setText(_translate("MainWindow", "U"))
        self.ElseButton.setText(_translate("MainWindow", "ELSE"))
        self.NewlineButton.setText(_translate("MainWindow", "|"))
        self.EqualButton.setText(_translate("MainWindow", "="))

