# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maindesign.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1863, 1353)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1, 1))
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.messagetextedit = QtWidgets.QTextEdit(self.centralwidget)
        self.messagetextedit.setGeometry(QtCore.QRect(19, 720, 256, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.messagetextedit.sizePolicy().hasHeightForWidth())
        self.messagetextedit.setSizePolicy(sizePolicy)
        self.messagetextedit.setMinimumSize(QtCore.QSize(3, 1))
        self.messagetextedit.setSizeIncrement(QtCore.QSize(1, 1))
        self.messagetextedit.setBaseSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        self.messagetextedit.setFont(font)
        self.messagetextedit.setReadOnly(True)
        self.messagetextedit.setObjectName("messagetextedit")
        self.obj10 = QtWidgets.QLabel(self.centralwidget)
        self.obj10.setGeometry(QtCore.QRect(335, 685, 22, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.obj10.sizePolicy().hasHeightForWidth())
        self.obj10.setSizePolicy(sizePolicy)
        self.obj10.setMinimumSize(QtCore.QSize(1, 1))
        self.obj10.setSizeIncrement(QtCore.QSize(1, 1))
        self.obj10.setBaseSize(QtCore.QSize(1, 1))
        self.obj10.setText("")
        self.obj10.setPixmap(QtGui.QPixmap("res/ball.png"))
        self.obj10.setScaledContents(True)
        self.obj10.setObjectName("obj10")
        self.obj2 = QtWidgets.QLabel(self.centralwidget)
        self.obj2.setGeometry(QtCore.QRect(55, 685, 23, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.obj2.sizePolicy().hasHeightForWidth())
        self.obj2.setSizePolicy(sizePolicy)
        self.obj2.setMinimumSize(QtCore.QSize(1, 1))
        self.obj2.setSizeIncrement(QtCore.QSize(1, 1))
        self.obj2.setBaseSize(QtCore.QSize(1, 1))
        self.obj2.setText("")
        self.obj2.setPixmap(QtGui.QPixmap("res/ball.png"))
        self.obj2.setScaledContents(True)
        self.obj2.setObjectName("obj2")
        self.obj12 = QtWidgets.QLabel(self.centralwidget)
        self.obj12.setGeometry(QtCore.QRect(404, 685, 23, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.obj12.sizePolicy().hasHeightForWidth())
        self.obj12.setSizePolicy(sizePolicy)
        self.obj12.setMinimumSize(QtCore.QSize(1, 1))
        self.obj12.setSizeIncrement(QtCore.QSize(1, 1))
        self.obj12.setBaseSize(QtCore.QSize(1, 1))
        self.obj12.setText("")
        self.obj12.setPixmap(QtGui.QPixmap("res/ball.png"))
        self.obj12.setScaledContents(True)
        self.obj12.setObjectName("obj12")
        self.obj13 = QtWidgets.QLabel(self.centralwidget)
        self.obj13.setGeometry(QtCore.QRect(439, 685, 23, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.obj13.sizePolicy().hasHeightForWidth())
        self.obj13.setSizePolicy(sizePolicy)
        self.obj13.setMinimumSize(QtCore.QSize(1, 1))
        self.obj13.setSizeIncrement(QtCore.QSize(1, 1))
        self.obj13.setBaseSize(QtCore.QSize(1, 1))
        self.obj13.setText("")
        self.obj13.setPixmap(QtGui.QPixmap("res/ball.png"))
        self.obj13.setScaledContents(True)
        self.obj13.setObjectName("obj13")
        self.obj11 = QtWidgets.QLabel(self.centralwidget)
        self.obj11.setGeometry(QtCore.QRect(369, 685, 23, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.obj11.sizePolicy().hasHeightForWidth())
        self.obj11.setSizePolicy(sizePolicy)
        self.obj11.setMinimumSize(QtCore.QSize(1, 1))
        self.obj11.setSizeIncrement(QtCore.QSize(1, 1))
        self.obj11.setBaseSize(QtCore.QSize(1, 1))
        self.obj11.setText("")
        self.obj11.setPixmap(QtGui.QPixmap("res/ball.png"))
        self.obj11.setScaledContents(True)
        self.obj11.setObjectName("obj11")
        self.obj15 = QtWidgets.QLabel(self.centralwidget)
        self.obj15.setGeometry(QtCore.QRect(509, 685, 23, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.obj15.sizePolicy().hasHeightForWidth())
        self.obj15.setSizePolicy(sizePolicy)
        self.obj15.setMinimumSize(QtCore.QSize(1, 1))
        self.obj15.setSizeIncrement(QtCore.QSize(1, 1))
        self.obj15.setBaseSize(QtCore.QSize(1, 1))
        self.obj15.setText("")
        self.obj15.setPixmap(QtGui.QPixmap("res/ball.png"))
        self.obj15.setScaledContents(True)
        self.obj15.setObjectName("obj15")
        self.obj18 = QtWidgets.QLabel(self.centralwidget)
        self.obj18.setGeometry(QtCore.QRect(614, 685, 23, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.obj18.sizePolicy().hasHeightForWidth())
        self.obj18.setSizePolicy(sizePolicy)
        self.obj18.setMinimumSize(QtCore.QSize(1, 1))
        self.obj18.setSizeIncrement(QtCore.QSize(1, 1))
        self.obj18.setBaseSize(QtCore.QSize(1, 1))
        self.obj18.setText("")
        self.obj18.setPixmap(QtGui.QPixmap("res/ball.png"))
        self.obj18.setScaledContents(True)
        self.obj18.setObjectName("obj18")
        self.obj16 = QtWidgets.QLabel(self.centralwidget)
        self.obj16.setGeometry(QtCore.QRect(544, 685, 23, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.obj16.sizePolicy().hasHeightForWidth())
        self.obj16.setSizePolicy(sizePolicy)
        self.obj16.setMinimumSize(QtCore.QSize(1, 1))
        self.obj16.setSizeIncrement(QtCore.QSize(1, 1))
        self.obj16.setBaseSize(QtCore.QSize(1, 1))
        self.obj16.setText("")
        self.obj16.setPixmap(QtGui.QPixmap("res/ball.png"))
        self.obj16.setScaledContents(True)
        self.obj16.setObjectName("obj16")
        self.obj19 = QtWidgets.QLabel(self.centralwidget)
        self.obj19.setGeometry(QtCore.QRect(649, 685, 23, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.obj19.sizePolicy().hasHeightForWidth())
        self.obj19.setSizePolicy(sizePolicy)
        self.obj19.setMinimumSize(QtCore.QSize(1, 1))
        self.obj19.setSizeIncrement(QtCore.QSize(1, 1))
        self.obj19.setBaseSize(QtCore.QSize(1, 1))
        self.obj19.setText("")
        self.obj19.setPixmap(QtGui.QPixmap("res/ball.png"))
        self.obj19.setScaledContents(True)
        self.obj19.setObjectName("obj19")
        self.obj20 = QtWidgets.QLabel(self.centralwidget)
        self.obj20.setGeometry(QtCore.QRect(684, 685, 23, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.obj20.sizePolicy().hasHeightForWidth())
        self.obj20.setSizePolicy(sizePolicy)
        self.obj20.setMinimumSize(QtCore.QSize(1, 1))
        self.obj20.setSizeIncrement(QtCore.QSize(1, 1))
        self.obj20.setBaseSize(QtCore.QSize(1, 1))
        self.obj20.setText("")
        self.obj20.setPixmap(QtGui.QPixmap("res/ball.png"))
        self.obj20.setScaledContents(True)
        self.obj20.setObjectName("obj20")
        self.obj3 = QtWidgets.QLabel(self.centralwidget)
        self.obj3.setGeometry(QtCore.QRect(90, 685, 23, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.obj3.sizePolicy().hasHeightForWidth())
        self.obj3.setSizePolicy(sizePolicy)
        self.obj3.setMinimumSize(QtCore.QSize(1, 1))
        self.obj3.setSizeIncrement(QtCore.QSize(1, 1))
        self.obj3.setBaseSize(QtCore.QSize(1, 1))
        self.obj3.setText("")
        self.obj3.setPixmap(QtGui.QPixmap("res/ball.png"))
        self.obj3.setScaledContents(True)
        self.obj3.setObjectName("obj3")
        self.obj7 = QtWidgets.QLabel(self.centralwidget)
        self.obj7.setGeometry(QtCore.QRect(230, 685, 23, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.obj7.sizePolicy().hasHeightForWidth())
        self.obj7.setSizePolicy(sizePolicy)
        self.obj7.setMinimumSize(QtCore.QSize(1, 1))
        self.obj7.setSizeIncrement(QtCore.QSize(1, 1))
        self.obj7.setBaseSize(QtCore.QSize(1, 1))
        self.obj7.setText("")
        self.obj7.setPixmap(QtGui.QPixmap("res/ball.png"))
        self.obj7.setScaledContents(True)
        self.obj7.setObjectName("obj7")
        self.obj14 = QtWidgets.QLabel(self.centralwidget)
        self.obj14.setGeometry(QtCore.QRect(474, 685, 23, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.obj14.sizePolicy().hasHeightForWidth())
        self.obj14.setSizePolicy(sizePolicy)
        self.obj14.setMinimumSize(QtCore.QSize(1, 1))
        self.obj14.setSizeIncrement(QtCore.QSize(1, 1))
        self.obj14.setBaseSize(QtCore.QSize(1, 1))
        self.obj14.setText("")
        self.obj14.setPixmap(QtGui.QPixmap("res/ball.png"))
        self.obj14.setScaledContents(True)
        self.obj14.setObjectName("obj14")
        self.obj1 = QtWidgets.QLabel(self.centralwidget)
        self.obj1.setGeometry(QtCore.QRect(20, 685, 23, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.obj1.sizePolicy().hasHeightForWidth())
        self.obj1.setSizePolicy(sizePolicy)
        self.obj1.setMinimumSize(QtCore.QSize(1, 1))
        self.obj1.setSizeIncrement(QtCore.QSize(1, 1))
        self.obj1.setBaseSize(QtCore.QSize(1, 1))
        self.obj1.setText("")
        self.obj1.setPixmap(QtGui.QPixmap("res/ball.png"))
        self.obj1.setScaledContents(True)
        self.obj1.setObjectName("obj1")
        self.obj6 = QtWidgets.QLabel(self.centralwidget)
        self.obj6.setGeometry(QtCore.QRect(195, 685, 23, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.obj6.sizePolicy().hasHeightForWidth())
        self.obj6.setSizePolicy(sizePolicy)
        self.obj6.setMinimumSize(QtCore.QSize(1, 1))
        self.obj6.setSizeIncrement(QtCore.QSize(1, 1))
        self.obj6.setBaseSize(QtCore.QSize(1, 1))
        self.obj6.setText("")
        self.obj6.setPixmap(QtGui.QPixmap("res/ball.png"))
        self.obj6.setScaledContents(True)
        self.obj6.setObjectName("obj6")
        self.obj4 = QtWidgets.QLabel(self.centralwidget)
        self.obj4.setGeometry(QtCore.QRect(125, 685, 23, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.obj4.sizePolicy().hasHeightForWidth())
        self.obj4.setSizePolicy(sizePolicy)
        self.obj4.setMinimumSize(QtCore.QSize(1, 1))
        self.obj4.setSizeIncrement(QtCore.QSize(1, 1))
        self.obj4.setBaseSize(QtCore.QSize(1, 1))
        self.obj4.setText("")
        self.obj4.setPixmap(QtGui.QPixmap("res/ball.png"))
        self.obj4.setScaledContents(True)
        self.obj4.setObjectName("obj4")
        self.obj5 = QtWidgets.QLabel(self.centralwidget)
        self.obj5.setGeometry(QtCore.QRect(160, 685, 23, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.obj5.sizePolicy().hasHeightForWidth())
        self.obj5.setSizePolicy(sizePolicy)
        self.obj5.setMinimumSize(QtCore.QSize(1, 1))
        self.obj5.setSizeIncrement(QtCore.QSize(1, 1))
        self.obj5.setBaseSize(QtCore.QSize(1, 1))
        self.obj5.setText("")
        self.obj5.setPixmap(QtGui.QPixmap("res/ball.png"))
        self.obj5.setScaledContents(True)
        self.obj5.setObjectName("obj5")
        self.obj9 = QtWidgets.QLabel(self.centralwidget)
        self.obj9.setGeometry(QtCore.QRect(300, 685, 23, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.obj9.sizePolicy().hasHeightForWidth())
        self.obj9.setSizePolicy(sizePolicy)
        self.obj9.setMinimumSize(QtCore.QSize(1, 1))
        self.obj9.setSizeIncrement(QtCore.QSize(1, 1))
        self.obj9.setBaseSize(QtCore.QSize(1, 1))
        self.obj9.setText("")
        self.obj9.setPixmap(QtGui.QPixmap("res/ball.png"))
        self.obj9.setScaledContents(True)
        self.obj9.setObjectName("obj9")
        self.obj8 = QtWidgets.QLabel(self.centralwidget)
        self.obj8.setGeometry(QtCore.QRect(265, 685, 23, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.obj8.sizePolicy().hasHeightForWidth())
        self.obj8.setSizePolicy(sizePolicy)
        self.obj8.setMinimumSize(QtCore.QSize(1, 1))
        self.obj8.setSizeIncrement(QtCore.QSize(1, 1))
        self.obj8.setBaseSize(QtCore.QSize(1, 1))
        self.obj8.setText("")
        self.obj8.setPixmap(QtGui.QPixmap("res/ball.png"))
        self.obj8.setScaledContents(True)
        self.obj8.setObjectName("obj8")
        self.obj17 = QtWidgets.QLabel(self.centralwidget)
        self.obj17.setGeometry(QtCore.QRect(579, 685, 23, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.obj17.sizePolicy().hasHeightForWidth())
        self.obj17.setSizePolicy(sizePolicy)
        self.obj17.setMinimumSize(QtCore.QSize(1, 1))
        self.obj17.setSizeIncrement(QtCore.QSize(1, 1))
        self.obj17.setBaseSize(QtCore.QSize(1, 1))
        self.obj17.setText("")
        self.obj17.setPixmap(QtGui.QPixmap("res/ball.png"))
        self.obj17.setScaledContents(True)
        self.obj17.setObjectName("obj17")
        self.LBracketButton = QtWidgets.QPushButton(self.centralwidget)
        self.LBracketButton.setGeometry(QtCore.QRect(1370, 747, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBracketButton.sizePolicy().hasHeightForWidth())
        self.LBracketButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.LBracketButton.setFont(font)
        self.LBracketButton.setObjectName("LBracketButton")
        self.NButton = QtWidgets.QPushButton(self.centralwidget)
        self.NButton.setGeometry(QtCore.QRect(722, 810, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NButton.sizePolicy().hasHeightForWidth())
        self.NButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.NButton.setFont(font)
        self.NButton.setObjectName("NButton")
        self.N1Button = QtWidgets.QPushButton(self.centralwidget)
        self.N1Button.setGeometry(QtCore.QRect(722, 684, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.N1Button.sizePolicy().hasHeightForWidth())
        self.N1Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.N1Button.setFont(font)
        self.N1Button.setObjectName("N1Button")
        self.UButton = QtWidgets.QPushButton(self.centralwidget)
        self.UButton.setGeometry(QtCore.QRect(1046, 810, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UButton.sizePolicy().hasHeightForWidth())
        self.UButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.UButton.setFont(font)
        self.UButton.setObjectName("UButton")
        self.EqualButton = QtWidgets.QPushButton(self.centralwidget)
        self.EqualButton.setGeometry(QtCore.QRect(1208, 810, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EqualButton.sizePolicy().hasHeightForWidth())
        self.EqualButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.EqualButton.setFont(font)
        self.EqualButton.setObjectName("EqualButton")
        self.FButton = QtWidgets.QPushButton(self.centralwidget)
        self.FButton.setGeometry(QtCore.QRect(722, 747, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FButton.sizePolicy().hasHeightForWidth())
        self.FButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.FButton.setFont(font)
        self.FButton.setObjectName("FButton")
        self.RBracketButton = QtWidgets.QPushButton(self.centralwidget)
        self.RBracketButton.setGeometry(QtCore.QRect(1532, 747, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RBracketButton.sizePolicy().hasHeightForWidth())
        self.RBracketButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.RBracketButton.setFont(font)
        self.RBracketButton.setObjectName("RBracketButton")
        self.NewlineButton = QtWidgets.QPushButton(self.centralwidget)
        self.NewlineButton.setGeometry(QtCore.QRect(1694, 684, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NewlineButton.sizePolicy().hasHeightForWidth())
        self.NewlineButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.NewlineButton.setFont(font)
        self.NewlineButton.setObjectName("NewlineButton")
        self.BackspaceButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackspaceButton.setGeometry(QtCore.QRect(1532, 684, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BackspaceButton.sizePolicy().hasHeightForWidth())
        self.BackspaceButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.BackspaceButton.setFont(font)
        self.BackspaceButton.setObjectName("BackspaceButton")
        self.LMBracketButton = QtWidgets.QPushButton(self.centralwidget)
        self.LMBracketButton.setGeometry(QtCore.QRect(1370, 810, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LMBracketButton.sizePolicy().hasHeightForWidth())
        self.LMBracketButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.LMBracketButton.setFont(font)
        self.LMBracketButton.setObjectName("LMBracketButton")
        self.N2Button = QtWidgets.QPushButton(self.centralwidget)
        self.N2Button.setGeometry(QtCore.QRect(884, 684, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.N2Button.sizePolicy().hasHeightForWidth())
        self.N2Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.N2Button.setFont(font)
        self.N2Button.setObjectName("N2Button")
        self.N3Button = QtWidgets.QPushButton(self.centralwidget)
        self.N3Button.setGeometry(QtCore.QRect(1046, 684, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.N3Button.sizePolicy().hasHeightForWidth())
        self.N3Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.N3Button.setFont(font)
        self.N3Button.setObjectName("N3Button")
        self.N5Button = QtWidgets.QPushButton(self.centralwidget)
        self.N5Button.setGeometry(QtCore.QRect(1370, 684, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.N5Button.sizePolicy().hasHeightForWidth())
        self.N5Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.N5Button.setFont(font)
        self.N5Button.setObjectName("N5Button")
        self.N4Button = QtWidgets.QPushButton(self.centralwidget)
        self.N4Button.setGeometry(QtCore.QRect(1208, 684, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.N4Button.sizePolicy().hasHeightForWidth())
        self.N4Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.N4Button.setFont(font)
        self.N4Button.setObjectName("N4Button")
        self.SButton = QtWidgets.QPushButton(self.centralwidget)
        self.SButton.setGeometry(QtCore.QRect(884, 810, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SButton.sizePolicy().hasHeightForWidth())
        self.SButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.SButton.setFont(font)
        self.SButton.setObjectName("SButton")
        self.RMBracketButton = QtWidgets.QPushButton(self.centralwidget)
        self.RMBracketButton.setGeometry(QtCore.QRect(1532, 810, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RMBracketButton.sizePolicy().hasHeightForWidth())
        self.RMBracketButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.RMBracketButton.setFont(font)
        self.RMBracketButton.setObjectName("RMBracketButton")
        self.LButton = QtWidgets.QPushButton(self.centralwidget)
        self.LButton.setGeometry(QtCore.QRect(884, 747, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LButton.sizePolicy().hasHeightForWidth())
        self.LButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.LButton.setFont(font)
        self.LButton.setObjectName("LButton")
        self.RunButton = QtWidgets.QPushButton(self.centralwidget)
        self.RunButton.setGeometry(QtCore.QRect(1694, 747, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunButton.sizePolicy().hasHeightForWidth())
        self.RunButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.RunButton.setFont(font)
        self.RunButton.setAutoFillBackground(False)
        self.RunButton.setObjectName("RunButton")
        self.StopButton = QtWidgets.QPushButton(self.centralwidget)
        self.StopButton.setGeometry(QtCore.QRect(1694, 810, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StopButton.sizePolicy().hasHeightForWidth())
        self.StopButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.StopButton.setFont(font)
        self.StopButton.setAutoFillBackground(False)
        self.StopButton.setObjectName("StopButton")
        self.RButton = QtWidgets.QPushButton(self.centralwidget)
        self.RButton.setGeometry(QtCore.QRect(1046, 747, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RButton.sizePolicy().hasHeightForWidth())
        self.RButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.RButton.setFont(font)
        self.RButton.setObjectName("RButton")
        self.BButton = QtWidgets.QPushButton(self.centralwidget)
        self.BButton.setGeometry(QtCore.QRect(1208, 747, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BButton.sizePolicy().hasHeightForWidth())
        self.BButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.BButton.setFont(font)
        self.BButton.setObjectName("BButton")
        self.IfButton = QtWidgets.QPushButton(self.centralwidget)
        self.IfButton.setGeometry(QtCore.QRect(722, 873, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IfButton.sizePolicy().hasHeightForWidth())
        self.IfButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.IfButton.setFont(font)
        self.IfButton.setObjectName("IfButton")
        self.ElseButton = QtWidgets.QPushButton(self.centralwidget)
        self.ElseButton.setGeometry(QtCore.QRect(884, 873, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ElseButton.sizePolicy().hasHeightForWidth())
        self.ElseButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.ElseButton.setFont(font)
        self.ElseButton.setObjectName("ElseButton")
        self.WhileButton = QtWidgets.QPushButton(self.centralwidget)
        self.WhileButton.setGeometry(QtCore.QRect(1046, 873, 150, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WhileButton.sizePolicy().hasHeightForWidth())
        self.WhileButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.WhileButton.setFont(font)
        self.WhileButton.setObjectName("WhileButton")
        self.label25 = QtWidgets.QLabel(self.centralwidget)
        self.label25.setEnabled(True)
        self.label25.setGeometry(QtCore.QRect(98, 335, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label25.sizePolicy().hasHeightForWidth())
        self.label25.setSizePolicy(sizePolicy)
        self.label25.setMinimumSize(QtCore.QSize(50, 50))
        self.label25.setSizeIncrement(QtCore.QSize(1, 1))
        self.label25.setBaseSize(QtCore.QSize(50, 50))
        self.label25.setFrameShape(QtWidgets.QFrame.Box)
        self.label25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label25.setLineWidth(1)
        self.label25.setText("")
        self.label25.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label25.setScaledContents(True)
        self.label25.setObjectName("label25")
        self.label42 = QtWidgets.QLabel(self.centralwidget)
        self.label42.setEnabled(True)
        self.label42.setGeometry(QtCore.QRect(256, 98, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label42.sizePolicy().hasHeightForWidth())
        self.label42.setSizePolicy(sizePolicy)
        self.label42.setMinimumSize(QtCore.QSize(50, 50))
        self.label42.setSizeIncrement(QtCore.QSize(1, 1))
        self.label42.setBaseSize(QtCore.QSize(50, 50))
        self.label42.setFrameShape(QtWidgets.QFrame.Box)
        self.label42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label42.setLineWidth(1)
        self.label42.setText("")
        self.label42.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label42.setScaledContents(True)
        self.label42.setObjectName("label42")
        self.label15 = QtWidgets.QLabel(self.centralwidget)
        self.label15.setEnabled(True)
        self.label15.setGeometry(QtCore.QRect(19, 335, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label15.sizePolicy().hasHeightForWidth())
        self.label15.setSizePolicy(sizePolicy)
        self.label15.setMinimumSize(QtCore.QSize(50, 50))
        self.label15.setSizeIncrement(QtCore.QSize(1, 1))
        self.label15.setBaseSize(QtCore.QSize(50, 50))
        self.label15.setFrameShape(QtWidgets.QFrame.Box)
        self.label15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label15.setLineWidth(1)
        self.label15.setText("")
        self.label15.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label15.setScaledContents(True)
        self.label15.setObjectName("label15")
        self.label43 = QtWidgets.QLabel(self.centralwidget)
        self.label43.setEnabled(True)
        self.label43.setGeometry(QtCore.QRect(256, 177, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label43.sizePolicy().hasHeightForWidth())
        self.label43.setSizePolicy(sizePolicy)
        self.label43.setMinimumSize(QtCore.QSize(50, 50))
        self.label43.setSizeIncrement(QtCore.QSize(1, 1))
        self.label43.setBaseSize(QtCore.QSize(50, 50))
        self.label43.setFrameShape(QtWidgets.QFrame.Box)
        self.label43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label43.setLineWidth(1)
        self.label43.setText("")
        self.label43.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label43.setScaledContents(True)
        self.label43.setObjectName("label43")
        self.label34 = QtWidgets.QLabel(self.centralwidget)
        self.label34.setEnabled(True)
        self.label34.setGeometry(QtCore.QRect(177, 256, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label34.sizePolicy().hasHeightForWidth())
        self.label34.setSizePolicy(sizePolicy)
        self.label34.setMinimumSize(QtCore.QSize(50, 50))
        self.label34.setSizeIncrement(QtCore.QSize(1, 1))
        self.label34.setBaseSize(QtCore.QSize(50, 50))
        self.label34.setFrameShape(QtWidgets.QFrame.Box)
        self.label34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label34.setLineWidth(1)
        self.label34.setText("")
        self.label34.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label34.setScaledContents(True)
        self.label34.setObjectName("label34")
        self.label44 = QtWidgets.QLabel(self.centralwidget)
        self.label44.setEnabled(True)
        self.label44.setGeometry(QtCore.QRect(256, 256, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label44.sizePolicy().hasHeightForWidth())
        self.label44.setSizePolicy(sizePolicy)
        self.label44.setMinimumSize(QtCore.QSize(50, 50))
        self.label44.setSizeIncrement(QtCore.QSize(1, 1))
        self.label44.setBaseSize(QtCore.QSize(50, 50))
        self.label44.setFrameShape(QtWidgets.QFrame.Box)
        self.label44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label44.setLineWidth(1)
        self.label44.setText("")
        self.label44.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label44.setScaledContents(True)
        self.label44.setObjectName("label44")
        self.label41 = QtWidgets.QLabel(self.centralwidget)
        self.label41.setEnabled(True)
        self.label41.setGeometry(QtCore.QRect(256, 19, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label41.sizePolicy().hasHeightForWidth())
        self.label41.setSizePolicy(sizePolicy)
        self.label41.setMinimumSize(QtCore.QSize(50, 50))
        self.label41.setSizeIncrement(QtCore.QSize(1, 1))
        self.label41.setBaseSize(QtCore.QSize(50, 50))
        self.label41.setFrameShape(QtWidgets.QFrame.Box)
        self.label41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label41.setLineWidth(1)
        self.label41.setText("")
        self.label41.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label41.setScaledContents(True)
        self.label41.setObjectName("label41")
        self.label21 = QtWidgets.QLabel(self.centralwidget)
        self.label21.setEnabled(True)
        self.label21.setGeometry(QtCore.QRect(98, 19, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label21.sizePolicy().hasHeightForWidth())
        self.label21.setSizePolicy(sizePolicy)
        self.label21.setMinimumSize(QtCore.QSize(50, 50))
        self.label21.setSizeIncrement(QtCore.QSize(1, 1))
        self.label21.setBaseSize(QtCore.QSize(50, 50))
        self.label21.setFrameShape(QtWidgets.QFrame.Box)
        self.label21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label21.setLineWidth(1)
        self.label21.setText("")
        self.label21.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label21.setScaledContents(True)
        self.label21.setObjectName("label21")
        self.label11 = QtWidgets.QLabel(self.centralwidget)
        self.label11.setEnabled(True)
        self.label11.setGeometry(QtCore.QRect(19, 19, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label11.sizePolicy().hasHeightForWidth())
        self.label11.setSizePolicy(sizePolicy)
        self.label11.setMinimumSize(QtCore.QSize(50, 50))
        self.label11.setSizeIncrement(QtCore.QSize(1, 1))
        self.label11.setBaseSize(QtCore.QSize(50, 50))
        self.label11.setFrameShape(QtWidgets.QFrame.Box)
        self.label11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label11.setLineWidth(1)
        self.label11.setText("")
        self.label11.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label11.setScaledContents(True)
        self.label11.setObjectName("label11")
        self.label31 = QtWidgets.QLabel(self.centralwidget)
        self.label31.setEnabled(True)
        self.label31.setGeometry(QtCore.QRect(177, 19, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label31.sizePolicy().hasHeightForWidth())
        self.label31.setSizePolicy(sizePolicy)
        self.label31.setMinimumSize(QtCore.QSize(50, 50))
        self.label31.setSizeIncrement(QtCore.QSize(1, 1))
        self.label31.setBaseSize(QtCore.QSize(50, 50))
        self.label31.setFrameShape(QtWidgets.QFrame.Box)
        self.label31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label31.setLineWidth(1)
        self.label31.setText("")
        self.label31.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label31.setScaledContents(True)
        self.label31.setObjectName("label31")
        self.label51 = QtWidgets.QLabel(self.centralwidget)
        self.label51.setEnabled(True)
        self.label51.setGeometry(QtCore.QRect(335, 19, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label51.sizePolicy().hasHeightForWidth())
        self.label51.setSizePolicy(sizePolicy)
        self.label51.setMinimumSize(QtCore.QSize(50, 50))
        self.label51.setSizeIncrement(QtCore.QSize(1, 1))
        self.label51.setBaseSize(QtCore.QSize(50, 50))
        self.label51.setFrameShape(QtWidgets.QFrame.Box)
        self.label51.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label51.setLineWidth(1)
        self.label51.setText("")
        self.label51.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label51.setScaledContents(True)
        self.label51.setObjectName("label51")
        self.label54 = QtWidgets.QLabel(self.centralwidget)
        self.label54.setEnabled(True)
        self.label54.setGeometry(QtCore.QRect(335, 256, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label54.sizePolicy().hasHeightForWidth())
        self.label54.setSizePolicy(sizePolicy)
        self.label54.setMinimumSize(QtCore.QSize(50, 50))
        self.label54.setSizeIncrement(QtCore.QSize(1, 1))
        self.label54.setBaseSize(QtCore.QSize(50, 50))
        self.label54.setFrameShape(QtWidgets.QFrame.Box)
        self.label54.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label54.setLineWidth(1)
        self.label54.setText("")
        self.label54.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label54.setScaledContents(True)
        self.label54.setObjectName("label54")
        self.label52 = QtWidgets.QLabel(self.centralwidget)
        self.label52.setEnabled(True)
        self.label52.setGeometry(QtCore.QRect(335, 98, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label52.sizePolicy().hasHeightForWidth())
        self.label52.setSizePolicy(sizePolicy)
        self.label52.setMinimumSize(QtCore.QSize(50, 50))
        self.label52.setSizeIncrement(QtCore.QSize(1, 1))
        self.label52.setBaseSize(QtCore.QSize(50, 50))
        self.label52.setFrameShape(QtWidgets.QFrame.Box)
        self.label52.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label52.setLineWidth(1)
        self.label52.setText("")
        self.label52.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label52.setScaledContents(True)
        self.label52.setObjectName("label52")
        self.label12 = QtWidgets.QLabel(self.centralwidget)
        self.label12.setEnabled(True)
        self.label12.setGeometry(QtCore.QRect(19, 98, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label12.sizePolicy().hasHeightForWidth())
        self.label12.setSizePolicy(sizePolicy)
        self.label12.setMinimumSize(QtCore.QSize(50, 50))
        self.label12.setSizeIncrement(QtCore.QSize(1, 1))
        self.label12.setBaseSize(QtCore.QSize(50, 50))
        self.label12.setFrameShape(QtWidgets.QFrame.Box)
        self.label12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label12.setLineWidth(1)
        self.label12.setText("")
        self.label12.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label12.setScaledContents(True)
        self.label12.setObjectName("label12")
        self.label35 = QtWidgets.QLabel(self.centralwidget)
        self.label35.setEnabled(True)
        self.label35.setGeometry(QtCore.QRect(177, 335, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label35.sizePolicy().hasHeightForWidth())
        self.label35.setSizePolicy(sizePolicy)
        self.label35.setMinimumSize(QtCore.QSize(50, 50))
        self.label35.setSizeIncrement(QtCore.QSize(1, 1))
        self.label35.setBaseSize(QtCore.QSize(50, 50))
        self.label35.setFrameShape(QtWidgets.QFrame.Box)
        self.label35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label35.setLineWidth(1)
        self.label35.setText("")
        self.label35.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label35.setScaledContents(True)
        self.label35.setObjectName("label35")
        self.label45 = QtWidgets.QLabel(self.centralwidget)
        self.label45.setEnabled(True)
        self.label45.setGeometry(QtCore.QRect(256, 335, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label45.sizePolicy().hasHeightForWidth())
        self.label45.setSizePolicy(sizePolicy)
        self.label45.setMinimumSize(QtCore.QSize(50, 50))
        self.label45.setSizeIncrement(QtCore.QSize(1, 1))
        self.label45.setBaseSize(QtCore.QSize(50, 50))
        self.label45.setFrameShape(QtWidgets.QFrame.Box)
        self.label45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label45.setLineWidth(1)
        self.label45.setText("")
        self.label45.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label45.setScaledContents(True)
        self.label45.setObjectName("label45")
        self.label23 = QtWidgets.QLabel(self.centralwidget)
        self.label23.setEnabled(True)
        self.label23.setGeometry(QtCore.QRect(98, 177, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label23.sizePolicy().hasHeightForWidth())
        self.label23.setSizePolicy(sizePolicy)
        self.label23.setMinimumSize(QtCore.QSize(50, 50))
        self.label23.setSizeIncrement(QtCore.QSize(1, 1))
        self.label23.setBaseSize(QtCore.QSize(50, 50))
        self.label23.setFrameShape(QtWidgets.QFrame.Box)
        self.label23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label23.setLineWidth(1)
        self.label23.setText("")
        self.label23.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label23.setScaledContents(True)
        self.label23.setObjectName("label23")
        self.label13 = QtWidgets.QLabel(self.centralwidget)
        self.label13.setEnabled(True)
        self.label13.setGeometry(QtCore.QRect(19, 177, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label13.sizePolicy().hasHeightForWidth())
        self.label13.setSizePolicy(sizePolicy)
        self.label13.setMinimumSize(QtCore.QSize(50, 50))
        self.label13.setSizeIncrement(QtCore.QSize(1, 1))
        self.label13.setBaseSize(QtCore.QSize(50, 50))
        self.label13.setFrameShape(QtWidgets.QFrame.Box)
        self.label13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label13.setLineWidth(1)
        self.label13.setText("")
        self.label13.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label13.setScaledContents(True)
        self.label13.setObjectName("label13")
        self.label53 = QtWidgets.QLabel(self.centralwidget)
        self.label53.setEnabled(True)
        self.label53.setGeometry(QtCore.QRect(335, 177, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label53.sizePolicy().hasHeightForWidth())
        self.label53.setSizePolicy(sizePolicy)
        self.label53.setMinimumSize(QtCore.QSize(50, 50))
        self.label53.setSizeIncrement(QtCore.QSize(1, 1))
        self.label53.setBaseSize(QtCore.QSize(50, 50))
        self.label53.setFrameShape(QtWidgets.QFrame.Box)
        self.label53.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label53.setLineWidth(1)
        self.label53.setText("")
        self.label53.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label53.setScaledContents(True)
        self.label53.setObjectName("label53")
        self.label32 = QtWidgets.QLabel(self.centralwidget)
        self.label32.setEnabled(True)
        self.label32.setGeometry(QtCore.QRect(177, 98, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label32.sizePolicy().hasHeightForWidth())
        self.label32.setSizePolicy(sizePolicy)
        self.label32.setMinimumSize(QtCore.QSize(50, 50))
        self.label32.setSizeIncrement(QtCore.QSize(1, 1))
        self.label32.setBaseSize(QtCore.QSize(50, 50))
        self.label32.setFrameShape(QtWidgets.QFrame.Box)
        self.label32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label32.setLineWidth(1)
        self.label32.setText("")
        self.label32.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label32.setScaledContents(True)
        self.label32.setObjectName("label32")
        self.label33 = QtWidgets.QLabel(self.centralwidget)
        self.label33.setEnabled(True)
        self.label33.setGeometry(QtCore.QRect(177, 177, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label33.sizePolicy().hasHeightForWidth())
        self.label33.setSizePolicy(sizePolicy)
        self.label33.setMinimumSize(QtCore.QSize(50, 50))
        self.label33.setSizeIncrement(QtCore.QSize(1, 1))
        self.label33.setBaseSize(QtCore.QSize(50, 50))
        self.label33.setFrameShape(QtWidgets.QFrame.Box)
        self.label33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label33.setLineWidth(1)
        self.label33.setText("")
        self.label33.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label33.setScaledContents(True)
        self.label33.setObjectName("label33")
        self.label22 = QtWidgets.QLabel(self.centralwidget)
        self.label22.setEnabled(True)
        self.label22.setGeometry(QtCore.QRect(98, 98, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label22.sizePolicy().hasHeightForWidth())
        self.label22.setSizePolicy(sizePolicy)
        self.label22.setMinimumSize(QtCore.QSize(50, 50))
        self.label22.setSizeIncrement(QtCore.QSize(1, 1))
        self.label22.setBaseSize(QtCore.QSize(50, 50))
        self.label22.setFrameShape(QtWidgets.QFrame.Box)
        self.label22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label22.setLineWidth(1)
        self.label22.setText("")
        self.label22.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label22.setScaledContents(True)
        self.label22.setObjectName("label22")
        self.label55 = QtWidgets.QLabel(self.centralwidget)
        self.label55.setEnabled(True)
        self.label55.setGeometry(QtCore.QRect(335, 335, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label55.sizePolicy().hasHeightForWidth())
        self.label55.setSizePolicy(sizePolicy)
        self.label55.setMinimumSize(QtCore.QSize(50, 50))
        self.label55.setSizeIncrement(QtCore.QSize(1, 1))
        self.label55.setBaseSize(QtCore.QSize(50, 50))
        self.label55.setFrameShape(QtWidgets.QFrame.Box)
        self.label55.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label55.setLineWidth(1)
        self.label55.setText("")
        self.label55.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label55.setScaledContents(True)
        self.label55.setObjectName("label55")
        self.label24 = QtWidgets.QLabel(self.centralwidget)
        self.label24.setEnabled(True)
        self.label24.setGeometry(QtCore.QRect(98, 256, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label24.sizePolicy().hasHeightForWidth())
        self.label24.setSizePolicy(sizePolicy)
        self.label24.setMinimumSize(QtCore.QSize(50, 50))
        self.label24.setSizeIncrement(QtCore.QSize(1, 1))
        self.label24.setBaseSize(QtCore.QSize(50, 50))
        self.label24.setFrameShape(QtWidgets.QFrame.Box)
        self.label24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label24.setLineWidth(1)
        self.label24.setText("")
        self.label24.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label24.setScaledContents(True)
        self.label24.setObjectName("label24")
        self.label14 = QtWidgets.QLabel(self.centralwidget)
        self.label14.setEnabled(True)
        self.label14.setGeometry(QtCore.QRect(19, 256, 79, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label14.sizePolicy().hasHeightForWidth())
        self.label14.setSizePolicy(sizePolicy)
        self.label14.setMinimumSize(QtCore.QSize(50, 50))
        self.label14.setSizeIncrement(QtCore.QSize(1, 1))
        self.label14.setBaseSize(QtCore.QSize(50, 50))
        self.label14.setFrameShape(QtWidgets.QFrame.Box)
        self.label14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label14.setLineWidth(1)
        self.label14.setText("")
        self.label14.setPixmap(QtGui.QPixmap("res/blank_small.png"))
        self.label14.setScaledContents(True)
        self.label14.setObjectName("label14")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(722, 19, 256, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FLR"))
        self.LBracketButton.setText(_translate("MainWindow", "("))
        self.NButton.setText(_translate("MainWindow", "N"))
        self.N1Button.setText(_translate("MainWindow", "1"))
        self.UButton.setText(_translate("MainWindow", "U"))
        self.EqualButton.setText(_translate("MainWindow", "="))
        self.FButton.setText(_translate("MainWindow", "F"))
        self.RBracketButton.setText(_translate("MainWindow", ")"))
        self.NewlineButton.setText(_translate("MainWindow", "|"))
        self.BackspaceButton.setText(_translate("MainWindow", "<-"))
        self.LMBracketButton.setText(_translate("MainWindow", "["))
        self.N2Button.setText(_translate("MainWindow", "2"))
        self.N3Button.setText(_translate("MainWindow", "3"))
        self.N5Button.setText(_translate("MainWindow", "5"))
        self.N4Button.setText(_translate("MainWindow", "4"))
        self.SButton.setText(_translate("MainWindow", "S"))
        self.RMBracketButton.setText(_translate("MainWindow", "]"))
        self.LButton.setText(_translate("MainWindow", "L"))
        self.RunButton.setText(_translate("MainWindow", "RUN"))
        self.StopButton.setText(_translate("MainWindow", "STOP"))
        self.RButton.setText(_translate("MainWindow", "R"))
        self.BButton.setText(_translate("MainWindow", "B"))
        self.IfButton.setText(_translate("MainWindow", "IF"))
        self.ElseButton.setText(_translate("MainWindow", "ELSE"))
        self.WhileButton.setText(_translate("MainWindow", "WHILE"))

